on: [push]

jobs:
  build:
    runs-on: docker
    container:
      image: fedora:41
    steps:
      - uses: https://codeberg.org/rotespferd/website@main
      - run: dnf install -y hugo
      - run: hugo version
      - run: pwd
      - run: ls -lsa
      - run: hugo