on: [push]

jobs:
  build:
    runs-on: docker
    container:
      image: fedora:41
    steps:
      - run: echo ${{ github.repository }}
      - uses: actions/checkout@v3
      - run: dnf install -y hugo
      - run: hugo version
      - run: pwd
      - run: ls -lsa
      - run: hugo